language: android
android:
  components:
    - build-tools-27.0.3
    - android-27
before_install:
  - ./gradlew decryptFiles
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_deploy:
- ./gradlew assembleRelease
- mv presentation/build/outputs/apk/release/presentation-release.apk presentation/build/outputs/apk/release/amiami.apk
deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file:
  - "presentation/build/outputs/apk/release/amiami.apk"
  skip_cleanup: true
  on:
    tags: true